### ISSUE TITLE
Feature request: use package.json engines block to specify node version

### ISSUE THREAD

**Issue by johnbeech** [bbc/speculate#18]
https://docs.npmjs.com/files/package.json#engines

Instead of using:

``` json
"spec": {
    "nodeVersion": "6.9.0"
}
```

Default to use the value in the engines block, e.g.:

``` json
{ "engines" : { "node" : "6.9.0" } }
```

**Comment by robinjmurphy** [comment]
This might be a good shout actually @johnbeech. I'll leave it with @bobbypates to look at.

**Comment by DaMouse404** [comment]
Apologies for the delayed reply, we've looked into this and found it's actually quite complicated to convert between node semver and rpm dependency versioning. One reason for this is that we have a nodejs package that has an [RPM epoch](http://rpm.org/max-rpm-snapshot/s1-rpm-depend-manual-dependencies.html#S3-RPM-DEPEND-VERSION-NOT-ENOUGH) of 2 and our version looks something like "< 2:7.0.0" otherwise it picks it up from the wrong repository. You'd also have to rewrite things such as the "~" operator and ">=0.10.3 <0.12" into something RPM-esque.

I think we're open to a Pull Request for this one if you can think of a nicer way of doing it but we're unlikely to build this functionality ourselves.

**Comment by nspragg** [comment]
No PR's have been raised for this issue, which is from 2016. Will reopen if required.
