### ISSUE TITLE
Override default log location

### ISSUE THREAD

**Issue by fusionfox** [bbc/speculate#19]
We used to specify a custom log location in our `project.json`:

```json
"custom_log_locations": [
  "/var/log/bbcthree-web-server/output.log"
]
```

It would be nice if we could do something similar in the `spec` block of `package.json` to override the default of 

```bash
StandardOutput=syslog
StandardError=syslog
```

set in https://github.com/bbc/speculate/blob/master/templates/service.mustache

**Comment by robinjmurphy** [comment]
Hi @fusionfox. I think we'd welcome any PRs that enable customisation of logging within the systemd spec. That said, we've moved to using `journalctl` because it's a nicer way to check your logs and you don't have to worry about log rotation, files etc. Take a look at https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

**Comment by fusionfox** [comment]
Took a look into this and it seems like it wouldn't be as straightforward as we thought to introduce a custom path for logging.

We've instead gone with redirecting the output of `npm start`: bbc/bbcthree-web@3ad47fec25f26b485fd783b68cd55078b8dbfdd3

Thanks for all the work that's been put into Speculate, it's really useful 😄

**Comment by robinjmurphy** [comment]
No worries. Glad you found a simple solution.
