### ISSUE TITLE
Could we have an Install hook?

### ISSUE THREAD

**Issue by Jayflux** [bbc/speculate#28]
So we can create custom directories for our service

**Comment by Limess** [comment]
To add an extra benefit of this, we can then add 
```exit 0``` 
to the end of the `%install` section to prevent `*.pyc` and `*.pyo` files being created by 'rpm helpers'. 
I'm not sure of a better way of disabling this using `rpmbuild` or `mock`, but it's causing us grief as a number of our bake-scripts are python.
https://stackoverflow.com/questions/30317213/how-to-remove-pyo-anc-pyc-from-an-rpm

Not sure if there's a better way than this to get them to `/etc/bake-scripts` and set permissions and without listing all file permissions:
```json
"post": [
            "find /etc/bake-scripts/application -maxdepth 1 -type f ! \\( -name \"*.pyc\" -or -name \"*.pyo\" \\) -exec chmod +x {} "
```

**Comment by DaMouse404** [comment]
@limess, is it worth adding that to `%install` anyway as part of the standard template? Or would it break something else for Node? I'm assuming it then tries to run all the `.pyc` files when it looks over all of the scripts?

When speculate finishes installing the service it is enabled but not started so it runs on the next boot of the system or if you run it with `systemctl start`. This means that most of the creating folders etc can be done in `post` rather than having to manage the entire RPM lifecycle. If we’re going to add hooks to each part of the lifecycle then the current `spec` format in `package.json` doesn’t work awfully well.

**Comment by Limess** [comment]
@DaMouse404 I'm not confident enough on the intricacies of building RPMs to comment sadly, I think we'd be ok given the focus on node project without breakage but wouldn't put my house on it. 

Regarding the `.pyc` and `.pyo` files, yes it just tries to run them unless you do some manual removal or more specific permission setting in `%post`.

Fair point with the 'adding to every hook'. Doing everything in `%post` just doesn't seem very idiomatic but I suppose that's the price paid for convenience here!

**Comment by Jayflux** [comment]
Yeah i think for now we may be fine with just using post

**Comment by DaMouse404** [comment]
Sounds good @Jayflux, going to close this but feel free to open a PR if you find you do need the support later 😸
