### ISSUE TITLE
Configure steps in spec file

### ISSUE THREAD

**Issue by robertson-ja** [bbc/speculate#6]
Could some of the steps in the generated spec file be optional/configurable? We would like to change the %build step but it doesn't seem possible. Thanks

**Comment by robinjmurphy** [comment]
Hi @robertson-ja. Can you let me know what you need to change, then we can decide how best to implement it.

**Comment by robertson-ja** [comment]
Hi

We wanted to fully remove %build npm rebuild from the spec file. We also wanted to add additional build dependancies to the BuildRequires attribute in the spec file.

Cheers

**Comment by robinjmurphy** [comment]
What are the build dependencies used for if you're not going to have a build step?

With speculate you should do all of your installing/testing/building first (outside of the RPM building environment) and _then_ you build the RPM.

It's important to keep the `npm rebuild` step because we [expect you to have already run `npm install`](https://github.com/bbc/speculate#install-your-dependencies-first) and  you'll want to rebuild any native modules for CentOS 7.

What does your build look like? What sort of things are you building?

**Comment by robertson-ja** [comment]
Manage to get build working without needing any changes made. Going to close. Many thanks for help.
